# This is a TOML document.

title = "env file"

[lf]
mysql = "asdq2e_lf"
token = "asdqe_lf"
etcd_path = "/dc/dsync_lf"
conn = 100
debug = true
redis_center = "toutiao.redis.conf.service.lf"

[hl]
mysql = "asdq2e_hl"
token = "asdqe_hl"
etcd_path = "/dc/dsync"
conn = 100
debug = false
redis_center = "toutiao.redis.conf.service.hl"

[lq]
mysql = "asdq2e_lq"
token = "asdqe_lq"
etcd_path = "/dc/dsync"
conn = 100
debug = false
redis_center = "toutiao.redis.conf.service.lq"